#!/usr/bin/env -S uv run --script
# /// script
# dependencies = ["nbtlib"]
# ///

import sys
import nbtlib

if len(sys.argv) != 3:
    print("Usage: add_loot.py <structure.nbt> <loot_table_id>")
    sys.exit(1)

path = sys.argv[1]
loot_table = sys.argv[2]

nbt = nbtlib.load(path)

count = 0
for block in nbt["blocks"]:
    be = block.get("nbt")
    if be and be.get("id") == "minecraft:chest":
        be["LootTable"] = nbtlib.String(loot_table)
        be["LootTableSeed"] = nbtlib.Long(0)
        count += 1

nbt.save()
print(f"Updated {count} chest(s) in {path}")
