#!/usr/bin/env -S uv run --script
# /// script
# dependencies = ["nbtlib"]
# ///

import sys
import nbtlib

if len(sys.argv) != 4:
    print("Usage: setup-spawners <structure.nbt> <normal_config> <ominous_config>")
    sys.exit(1)

path = sys.argv[1]
normal_config = sys.argv[2]
ominous_config = sys.argv[3]

nbt = nbtlib.load(path)

count = 0
for block in nbt["blocks"]:
    be = block.get("nbt")
    if not be:
        continue

    if be.get("id") == "minecraft:trial_spawner":
        be["normal_config"] = nbtlib.String(normal_config)
        be["ominous_config"] = nbtlib.String(ominous_config)
        be.pop("spawn_data", None)
        count += 1

nbt.save()
print(f"Updated {count} block(s) in {path}")