license="${mod_license}"
issueTrackerURL="https://github.com/outurnate/sargasso/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

updateJSONURL = "https://api.modrinth.com/updates/sargasso/forge_updates.json"
displayURL="https://modrinth.com/project/sargasso"
logoFile="pack.png"
credits="${mod_credits}. Contains code originally from OpenBlocks"
authors="panicnot42, AlexanderRSM, Tarn_K, nebularzzz"

description='''
The land of the lost, a dimension where everything ever lost is found.
'''
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config="META-INF/${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="fusion"
type="required"
versionRange="[${fusion_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="modonomicon"
type="required"
versionRange="[${modonomicon_version},)"
ordering="NONE"
side="BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"